# Generated by Django 3.2.8 on 2023-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='name',
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
